#config_version=5
# NOBS 

mode:
    start_events: ball_started
    priority: 200
    code: rotomove.RotoMove

counters:
    rotocount:
        count_events: dingwalls_hit, slings_hit
        starting_count: 3
        count_complete_value: 9
        direction: up
        reset_on_complete: true
        persist_state: true
        disable_on_complete: false

scoring:
    extraball_hit:      
        score: 1 * current_player.dpegs

  
    rototarget_hit{machine.roto<10}:
        score: machine.roto * current_player.dpegs

     
    rototarget_hit{machine.roto>9}:
        score: 10 * current_player.dpegs

event_player:

    machine_var_roto:
        roto_(machine.rotopos)

