#config_version=5
# NOBS 

mode:
    start_events: ball_starting
    priority: 200
    code: rotomove.RotoMove

counters:
    rotocount:
        count_events: dingwalls_hit, slings_hit
        starting_count: 4
        count_complete_value: 11
        direction: up
        reset_on_complete: true
        persist_state: true
        disable_on_complete: false

scoring:
    extraball_hit:      
        score: 1 * current_player.dpegs

  
    rototarget_hit{machine.roto<10}:
        score: machine.roto * current_player.dpegs

     
    rototarget_hit{machine.roto>9}:
        score: 10 * current_player.dpegs

event_player:

    game_started:
        roto_(machine.rotopos)

    machine_var_roto:
        roto_(machine.rotopos)

