#config_version=6
# NOBS
#
#   Skill shot mode: hit flashing top lane on plunge to be awarded heels - 2 pegs.

mode:
    start_events: ball_starting
    stop_events: 
        - award_heels
        - sw_skill_cancel
    priority: 200

        
#############################################################
# SHOTS
#############################################################

shots:
    skill_shot_l:
        advance_events: skill_advance_1
        switch: s_ro_king
        profile: p_skill_shot
        show_tokens:
            leds: l_topk
    skill_shot_m:
        advance_events: skill_advance_2
        switch: s_ro_queen
        profile: p_skill_shot
        show_tokens:
            leds: l_topq
    skill_shot_r:
        advance_events: skill_advance_3
        switch: s_ro_jack
        profile: p_skill_shot
        show_tokens:
            leds: l_topj

#############################################################
# BALL SAVE
#############################################################
ball_saves:
    skill_shot_bs:
        balls_to_save: -1
        auto_launch: true

#############################################################
# SHOT PROFILES
#############################################################

shot_profiles:
    p_skill_shot:
        block: false   #CLEAR LANE HIT
        advance_on_hit: false
        states:
            - name: unlit
              show: off
            - name: lit
              show: flash
              loops: -1
              speed: 4
            - name: hit
              show: on

#############################################################
# SHOT GROUPS
#############################################################

shot_groups:
    skill_shot:
        shots: skill_shot_l, skill_shot_m, skill_shot_r
        reset_events: mode_skill_shot_starting


#############################################################
# RANDOM EVENT PLAYER:  select random shot for skill shot
#############################################################

random_event_player:              
    mode_skill_shot_started:
        events:
            - skill_advance_1
            - skill_advance_2
            - skill_advance_3

#############################################################
# EVENT PLAYER:  play events when events occur :)
#############################################################

event_player:
    skill_shot_unlit_hit: sw_skill_cancel
    skill_shot_lit_hit: award_heels

#############################################################
# SEGMENT PLAYER:  update score displays
#############################################################

segment_display_player:
    mode_skill_shot_started{current_player.number==1}: 
        upperpegs:
            flashing: all
            text: "{players[0].score:0>2}"
        uppergames:
            flashing: all
            text: "{players[0].games:,d}"

    mode_skill_shot_started{current_player.number==2}: 
        lowerpegs:
            flashing: all
            text: "{players[1].score:0>2}"
        lowergames:
            flashing: all
            text: "{players[1].games:,d}"
    
