#config_version=5
# NOBS

show_player:
  mode_attract_started: 
    attract_light_show:
      speed: 8
    attract_seg_show:
      speed: 1
    attract_board_show:
      speed: 20

event_player:
    mode_attract_started:
        roto_(machine.rotopos)