#config_version=6
# NOBS 

mpf:
    report_crashes: never

config:
    - leds.yaml
    - keys.yaml
    - servos.yaml
    - switches.yaml
    - displays.yaml

scriptlets: 
    cboard.Cboard
    # resetroto.RotoReset

hardware:
    platform: opp
    driverboards: gen2
    lights: fadecandy
    servo_controllers: pololu_maestro

fadecandy:
    whitepoint: [0.5, 0.5, 0.5]   #set overall brightness or lower individual RGB

opp:
    ports: COM3
    poll_hz: 50
    debug: true

modes:
    - base
    - high_score
    - ebmode
    - skill_shot
    - roto
    - tilt

player_vars:
    dpegs:
        initial_value: 1

machine_vars:
    rotodir:                 # the direction the roto target is moving -1 for counterclockwise, 1 for clockwise
        initial_value: 1
        persist: true
    rotopos:
        initial_value: 1     # the servo position number 1-39
        persist: true
    roto:
        initial_value: 1     # the value 1-13 the roto target
        persist: true
    player1games:
        initial_value: 0
    player2games:
        initial_value: 0
       
game:
    balls_per_game: 3
    max_players: 2

light_settings:
    default_fade_ms: 200

playfields:
    playfield:
        tags: default
        default_source_device: bd_drain

ball_devices:
    bd_drain:
        ball_switches: s_drain
        eject_coil: c_drain_eject
        debug: true
        eject_timeouts: 3s
        tags: drain, home, trough

queue_relay_player:
    balldevice_bd_drain_ball_eject_attempt:
        post: timetoeject
        wait_for: timer_ejecttimer_complete


#
coils:
    c_drain_eject:
        number: 1-7
        default_pulse_ms: 250
    c_flipper_left_main:
        number: 1-0
        default_pulse_ms: 50ms
        default_hold_power: 0.15
    # c_flipper_left_hold:
        # number: 1-1
        allow_enable: true   
    c_flipper_right_main:
        number: 1-2
        default_pulse_ms: 50ms
        default_hold_power: 0.15
    # c_flipper_right_hold:
        # number: 1-3
        allow_enable: true   
    c_sling:
        number: 0-2
        default_pulse_ms: 40
    c_leftDTreset:
        number: 1-4
        default_pulse_ms: 100
    c_midDTreset:
        number: 1-6
        default_pulse_ms: 60
    c_rightDTreset:
        number: 1-5
        default_pulse_ms: 60
    c_pop_left:
        number: 0-0
        default_pulse_ms: 30
    c_pop_right:
        number: 0-1
        default_pulse_ms: 30
    c_knocker:
        number: 0-7
        default_pulse_ms: 40
        pulse_events:
            - player_games
    c_chime10:
        number: 0-4
        default_pulse_ms: 20
        pulse_events:
            - dingwalls_hit
            - slings_hit
            - handa_hit
            - handb_hit
            - handc_hit
            - handd_hit
    c_chime100:
        number: 0-5
        default_pulse_ms: 20
        pulse_events:
            - s_pop_left_active
            - s_pop_right_active
    c_chime1000:
        number: 0-6
        default_pulse_ms: 20
        pulse_events:
            - player_score{value>0}
#
autofire_coils:
  slingshot:
    coil: c_sling
    switch: s_sling
  left_pop:
    coil: c_pop_left
    switch: s_pop_left
  right_pop:
    coil: c_pop_right
    switch: s_pop_right
#
drop_targets:
    dt_6:
        switch: s_drop_6
    dt_5:
        switch: s_drop_5
    dt_5b:
        switch: s_drop_5b
    dt_4:
        switch: s_drop_4
    dt_ace:
        switch: s_drop_ace
    dt_2:
        switch: s_drop_2
    dt_3:
        switch: s_drop_3
    dt_6r:
        switch: s_drop_6_right
    dt_9:
        switch: s_drop_9
# 
drop_target_banks:
    dtleft:
        drop_targets: dt_6, dt_5, dt_5b, dt_4
        reset_coil: c_leftDTreset
        reset_events:
            ball_started: 1.75s
            handb_complete: 2.5s
        
    dtmid:
        drop_targets: dt_ace, dt_2, dt_3
        reset_coil: c_midDTreset
        reset_events:
            ball_started: 2.25s
            handa_complete: 2.5s

    dtright:
        drop_targets: dt_6r, dt_9
        reset_coil: c_rightDTreset
        reset_events:
            ball_started: 2.75s
            handc_complete: 2.5s
#
flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        # hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        # hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
#
#############################################################
# SHOW PLAYER:  play shows on events
#############################################################

show_player:
    player_added{num==1}: 
        chimeinit1:
            loops: 0
    player_added{num==2}: 
        chimeinit2:
            loops: 0


#############################################################
# SLIDE PLAYER:  play slides on events
#############################################################

slide_player:
    mc_ready: # when the mc (Media Center) is ready start the...
        layout: # layout slide on the..
            target: window # ENTIRE Window

    init_done:    #when init is done put the base images up
        background:
            target: backglass
        upperpegssegment:
            target: upperpegsdisplay
        uppergamessegment:
            target: uppergamesdisplay
        lowerpegssegment:
            target: lowerpegsdisplay
        lowergamessegment:
            target: lowergamesdisplay
        bipsegment:
            target: bipdisplay
  
    game_starting:
        background_lit:
            target: backglass
    game_ended:
        background:
            target: backglass



#############################################################
# SEGMENT PLAYER:  update score displays
#############################################################

segment_display_player:
  update_segment_display_score:
    upperpegs:
      flashing: off
      color: 00acf0
      text: "{players[0].score:0>2}"
    uppergames:
      flashing: off
      color: 00acf0
      text: "{players[0].games:,d}"
    lowerpegs:
      flashing: off
      color: 00acf0
      text:  "{players[1].score:0>2}"
    lowergames:
      flashing: off
      color: 00acf0
      text:  "{players[1].games:,d}"
  ball_started:
    bipseg:
      color: 00acf0
      text: "{current_player.ball:d}"
  game_ending:
    bipseg:
      text: ""
