#config_version=5
# NOBS 

config:
    - leds.yaml
    - keys.yaml
    - servos.yaml

scriptlets: 
    cboard.Cboard
    # resetroto.RotoReset

hardware:
    platform: opp
    driverboards: gen2
    lights: fadecandy
    servo_controllers: pololu_maestro

fadecandy:
    whitepoint: [0.8, 0.8, 0.8]   #set overall brightness or lower individual RGB

opp:
    ports: COM3
    poll_hz: 50
    debug: true

modes:
    - base
    - high_score
    - ebmode
    - skill_shot
    - roto
    - tilt

player_vars:
    dpegs:
        initial_value: 1

machine_vars:
    rotodir:                 # the direction the roto target is moving -1 for counterclockwise, 1 for clockwise
        initial_value: 1
        persist: true
    rotopos:
        initial_value: 1     # the servo position number 1-39
        persist: true
    roto:
        initial_value: 1     # the value 1-13 the roto target
        persist: true
    player1games:
        initial_value: 0
    player2games:
        initial_value: 0
       
game:
    balls_per_game: 3
    max_players: 2

light_settings:
    default_fade_ms: 200

playfields:
    playfield:
        tags: default
        default_source_device: bd_drain

ball_devices:
    bd_drain:
        ball_switches: s_drain
        eject_coil: c_drain_eject
        debug: true
        tags: drain, home, trough, ball_add_live

queue_relay_player:
    balldevice_bd_drain_ball_eject_attempt:
        post: timetoeject
        wait_for: timer_ejecttimer_complete

switches:
    s_left_flipper:
        number: 1-0
        tags: left_flipper
    s_right_flipper:
        number: 1-2
        tags: right_flipper
    s_drain:
        number: 1-16
        tags: drain
    s_start:
        number: 0-25
        tags: start
    s_left_inlane:
        number: 1-18
        tags: playfield_active
    s_left_outlane:
        number: 1-17
        tags: playfield_active
    s_right_outlane:
        number: 1-19
        tags: playfield_active
    s_drop_6:
        number: 1-20
        tags: playfield_active
    s_drop_5:
        number: 1-21
        tags: playfield_active
    s_drop_5b:
        number: 1-22
        tags: playfield_active
    s_drop_4:
        number: 1-23
        tags: playfield_active
    s_drop_ace:
        number: 1-24
        tags: playfield_active
    s_drop_2:
        number: 1-25
        tags: playfield_active
    s_drop_3:
        number: 1-26
        tags: playfield_active
    s_drop_6_right:
        number: 1-27
        tags: playfield_active
    s_drop_9:
        number: 1-28
        tags: playfield_active
    s_extra_ball:
        number: 1-29
        tags: playfield_active
    s_ro_2:
        number: 1-30
        tags: playfield_active
    s_ro_king:
        number: 0-21
        tags: playfield_active
    s_ro_queen:
        number: 0-22
        tags: playfield_active
    s_ro_jack:
        number: 0-23
        tags: playfield_active
    s_star1:
        number: 0-16
        tags: playfield_active
    s_star2:
        number: 0-17
        tags: playfield_active
    s_star3:
        number: 0-18
        tags: playfield_active
    s_star4:
        number: 0-19
        tags: playfield_active
    s_star5:
        number: 0-20
        tags: playfield_active
    s_roto:
        number: 0-24
        tags: playfield_active
    s_dingwalls:
        number: 0-26
        tags: playfield_active
    s_tiltbob:
        number: 0-27
        tags: tilt_warning
    s_sling:
        number: 0-2
        tags: playfield_active
    s_pop_left:
        number: 0-0
        tags: playfield_active
    s_pop_right:
        number: 0-1
        tags: playfield_active
# 
#
coils:
    c_drain_eject:
        number: 1-7
        default_pulse_ms: 200
    c_flipper_left_main:
        number: 1-0
        default_pulse_ms: 50ms
        default_hold_power: 1.0
    # c_flipper_left_hold:
    #     number: 1-1
    #     pulse_ms: 250
    #     hold_power16: 15
    c_flipper_right_main:
        number: 1-2
        default_pulse_ms: 50ms
        default_hold_power: 1.0
    # c_flipper_right_hold:
    #     number: 1-3
    #     pulse_ms: 250
    #     hold_power16: 15
    c_sling:
        number: 0-2
        default_pulse_ms: 40
    c_leftDTreset:
        number: 1-4
        default_pulse_ms: 100
    c_midDTreset:
        number: 1-6
        default_pulse_ms: 60
    c_rightDTreset:
        number: 1-5
        default_pulse_ms: 60
    c_pop_left:
        number: 0-0
        default_pulse_ms: 30
    c_pop_right:
        number: 0-1
        default_pulse_ms: 30
    c_knocker:
        number: 0-7
        default_pulse_ms: 40
        pulse_events:
            player_games
    c_chime10:
        number: 0-4
        default_pulse_ms: 20
        pulse_events:
            dingwalls_hit
            slings_hit
            handa_hit
            handb_hit
            handc_hit
            handd_hit
    c_chime100:
        number: 0-5
        default_pulse_ms: 20
        pulse_events:
            s_pop_left_active
            s_pop_right_active
    c_chime1000:
        number: 0-6
        default_pulse_ms: 20
        pulse_events:
            player_score{value>0}
#
autofire_coils:
  slingshot:
    coil: c_sling
    switch: s_sling
  left_pop:
    coil: c_pop_left
    switch: s_pop_left
  right_pop:
    coil: c_pop_right
    switch: s_pop_right
#
drop_targets:
    dt_6:
        switch: s_drop_6
    dt_5:
        switch: s_drop_5
    dt_5b:
        switch: s_drop_5b
    dt_4:
        switch: s_drop_4
    dt_ace:
        switch: s_drop_ace
    dt_2:
        switch: s_drop_2
    dt_3:
        switch: s_drop_3
    dt_6r:
        switch: s_drop_6_right
    dt_9:
        switch: s_drop_9
# 
drop_target_banks:
    dtleft:
        drop_targets: dt_6, dt_5, dt_5b, dt_4
        reset_coil: c_leftDTreset
        reset_events:
            ball_started: 1.75s
            handb_complete: 2.5s
        
    dtmid:
        drop_targets: dt_ace, dt_2, dt_3
        reset_coil: c_midDTreset
        reset_events:
            ball_started: 2.25s
            handa_complete: 2.5s

    dtright:
        drop_targets: dt_6r, dt_9
        reset_coil: c_rightDTreset
        reset_events:
            ball_started: 2.75s
            handc_complete: 2.5s
#
flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        # hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        # hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
#

show_player:
    player_added{num==1}: 
        chimeinit1:
            loops: 0
    player_added{num==2}: 
        chimeinit2:
            loops: 0

#
displays:
  window:
    width: 1280
    height: 1024
#
window:
  title: NOBS
  width: 1280
  height: 1024    
  resizable: false
  fullscreen: false
  borderless: true
  exit_on_escape: true
  source_display: window
#
slides:

  nobs_running_slide:
    widgets:
      - type: image
        image: nobs_bg
        z: 1
      - type: text
        text: (player1|score)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 620
        y: 644
        font_size: 240
        anchor_x: right
        anchor_y: bottom
        z: 2
      - type: text
        text: (player1|games)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 620
        y: 84        
        font_size: 240
        anchor_x: right
        anchor_y: bottom
        z: 2

      - type: text
        text: (player2|score)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 1230
        y: 644        
        font_size: 240
        anchor_x: right
        anchor_y: bottom
        z: 2
      - type: text
        text: (player2|games)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 1230
        y: 84        
        font_size: 240
        anchor_x: right
        anchor_y: bottom
        z: 2

      - type: text
        text: (ball)
        font_name: Ten_segment
        color: blue
        x: 1230
        y: 404        
        anchor_x: right
        anchor_y: bottom
        font_size: 145
        z: 2
#