#config_version=4
# NOBS 

virtual_platform_start_active_switches:
    s_drain

Machine:
    Balls_Installed: 1
#
hardware:
    platform: opp
    driverboards: gen2
    leds: fadecandy
    # servo_controllers: pololu_maestro
    servo_controllers: smart_virtual

opp:
    ports: COM3
    poll_hz: 50

# pololu_maestro:
#     port: COM4

modes:
    - base
    - high_score
    - ebmode
    - skill_shot
    - roto
    - tilt

player_vars:
    dpegs:
        initial_value: 1

machine_vars:
    roto:
        initial_value: 1
    player1games:
        initial_value: 0
    player2games:
        initial_value: 0

        
game:
    balls_per_game: 3
    Max_players: 2


servos:
    servo_lout:
        number: 1
        positions:
            0.2: servo_lout_closed
            0.8: servo_lout_open
        reset_position: 0.2
        reset_events: handd2_complete, ball_started
    servo_rout:
        number: 2
        positions:
            0.2: servo_rout_closed
            0.8: servo_rout_open
        reset_position: 0.2
        reset_events: ball_started
    servo_roto:
        number: 0
        positions:
            0.1: roto_1
            0.15: roto_2
            0.2: roto_3
            0.25: roto_4
            0.30: roto_5
            0.35: roto_6
            0.40: roto_7
            0.45: roto_8
            0.50: roto_9
            0.55: roto_10
            0.60: roto_11
            0.65: roto_12
            0.70: roto_13
        reset_events: service_mode_entered
shots:
    dingwalls:
        switch: s_dingwalls
    left_outlane:
        switch: s_left_outlane
        show_tokens:
            led: l_leftout
        profile: p_onoff
    left_outlane2:
        switch: s_left_outlane
        show_tokens:
            led: l_handd5
        profile: p_offon
    left_inlane:
        switch: s_left_inlane
        show_tokens:
            led: l_leftin
        profile: p_onoff
    left_inlane2:
        switch: s_left_inlane
        show_tokens:
            leds: l_handc7
        profile: p_offon
    left_inlane3:
        switch: s_left_inlane
        show_tokens:
            leds: l_star5
        profile: p_offon
    droptarget_6:
        switch: s_drop_6
        show_tokens:
            led: l_handB6
        profile: p_offon
    droptarget_5:
        switch: s_drop_5
        show_tokens:
            led: l_handB5
        profile: p_offon
    droptarget_5b:
        switch: s_drop_5b
        show_tokens:
            led: l_handB5b
        profile: p_offon
    droptarget_4:    
        switch: s_drop_4
        show_tokens:
            led: l_handB4
        profile: p_offon
    droptarget_6b:
        switch: s_drop_6_right
        show_tokens:
            led: l_handc6
        profile: p_offon
    droptarget_9:
        switch: s_drop_9
        show_tokens:
            led: l_handc9
        profile: p_offon
    right_outlane:
        switch: s_right_outlane
        show_tokens:
            led: l_rightout
        profile: p_onoff
    right_outlane2:
        switch: s_right_outlane
        show_tokens:
            leds: l_handc8
        profile: p_offon
    right_outlane3:
        switch: s_right_outlane
        show_tokens:
            leds: l_star4
        profile: p_offon
    droptarget_A:    
        switch: s_drop_ace
        show_tokens:
            led: l_handAa
        profile: p_offon
    droptarget_2:    
        switch: s_drop_2
        show_tokens:
            led: l_handA2
        profile: p_offon
    droptarget_3:    
        switch: s_drop_3
        show_tokens:
            led: l_handA3
        profile: p_offon
    right_2:
        switch: s_ro_2
        show_tokens:
            led: l_right2
        profile: p_onoff
    right_22:
        switch: s_ro_2
        show_tokens:
            led: l_handA2b
        profile: p_offon
    top_king:
        switch: s_ro_king
        show_tokens:
            led: l_topK
        profile: p_onoff
    top_king2:
        switch: s_ro_king
        show_tokens:
            leds: l_handdk
        profile: p_offon
    top_king3:
        switch: s_ro_king
        show_tokens:
            leds: l_star1
        profile: p_offon
    top_queen:
        switch: s_ro_queen
        show_tokens:
            led: l_topQ
        profile: p_onoff
    top_queen2:
        switch: s_ro_queen
        show_tokens:
            leds: l_handdq
        profile: p_offon
    top_queen3:
        switch: s_ro_queen
        show_tokens:
            leds: l_star2
        profile: p_offon
    top_jack:
        switch: s_ro_jack
        show_tokens:
            led: l_topJ
        profile: p_onoff
    top_jack2:
        switch: s_ro_jack
        show_tokens:
            leds: l_handdj
        profile: p_offon
    top_jack3:
        switch: s_ro_jack
        show_tokens:
            leds: l_star3
        profile: p_offon
    star1:
        switch: s_star1
    star2:
        switch: s_star2
    star3:
        switch: s_star3
    star4:
        switch: s_star4
    star5:
        switch: s_star5
    extraball:
        switch: s_extra_ball
    rototarget:
        switch: s_roto
    slings:
        switch: s_sling

#
#
shot_groups:
    handa: 
        shots: droptarget_A, droptarget_2, droptarget_3, right_22
        reset_events:
            # ball_starting: 1
            handa_complete: 3s
    handa2:
        shots: right_2
        reset_events:
            # ball_starting: 1
            handa_complete: 3s
    handb:
        shots: droptarget_4, droptarget_5, droptarget_5b, droptarget_6
        reset_events:
            # ball_starting: .5s
            handb_complete: 3.25s
    handc:
        shots: left_inlane2, droptarget_6b, droptarget_9, right_outlane2
        reset_events:
            # ball_starting: 1.5s
            handc_complete: 3.5s
    handc2:
        shots: left_inlane, right_outlane
        reset_events:
            # ball_starting: 1.5s
            handc_complete: 3.5s
    handd:
        shots: left_outlane, top_jack, top_queen, top_king
        reset_events:
            # ball_starting: 0s
            handd_complete: 3.75s
    handd2:
        shots: left_outlane2, top_jack2, top_queen2, top_king2
        reset_events:
            # ball_starting: 0s
            handd_complete: 3.75s
    stars:
        shots: left_inlane3, right_outlane3, top_jack3, top_queen3, top_king3
        reset_events:
            ball_starting: 1s
#
shot_profiles:
    p_onoff:
        states:
            - name: lit # step 1
              show: on
            - name: unlit  # step 2
              show: off
        loop: no
    p_offon:
        states:
            - name: unlit # step 1
              show: off
            - name: lit  # step 2
              show: on
        loop: no
#
keyboard:
  z:
    switch: s_left_flipper
  "/":
    switch: s_right_flipper
  "?":
    switch: s_right_flipper
  1:
    switch: s_drain
    toggle: true
  s:
    switch: s_start
  3:
    switch: s_star1
  4:
    switch: s_star2
  5:
    switch: s_star3
  6:
    switch: s_star4
  7:
    switch: s_star5
  9:
    switch: s_pop_left
  0:
    switch: s_pop_right
  q:
    switch: s_drop_6
  w:
    switch: s_drop_5
  e:
    switch: s_drop_5b
  r:
    switch: s_drop_4
  y:
    switch: s_ro_king
  u:
    switch: s_ro_queen
  i:
    switch: s_ro_jack
  o:
    switch: s_left_outlane
  p:
    switch: s_dingwalls
  d:
    switch: s_drop_ace
  f:
    switch: s_drop_2
  g:
    switch: s_drop_3
  h:
    switch: s_ro_2
  k:
    switch: s_extra_ball
  l:
    switch: s_roto
  x:
    switch: s_drop_9
  c:
    switch: s_drop_6_right
  v:
    switch: s_left_inlane
  b:
    switch: s_right_outlane
  m:
    switch: s_sling 
  t:
    switch: s_tiltbob
#
ball_devices:
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain_eject
    debug: true
    tags: drain, home, trough, ball_add_live

switches:
    s_left_flipper:
        number: 1-0
        tags: left_flipper
    s_right_flipper:
        number: 1-2
        tags: right_flipper
    s_drain:
        number: 1-16
        tags: drain
    s_start:
        number: 0-25
        tags: start
    s_left_inlane:
        number: 1-18
        tags: playfield_active
    s_left_outlane:
        number: 1-17
        tags: playfield_active
    s_right_outlane:
        number: 1-19
        tags: playfield_active
    s_drop_6:
        number: 1-20
        tags: playfield_active
    s_drop_5:
        number: 1-21
        tags: playfield_active
    s_drop_5b:
        number: 1-22
        tags: playfield_active
    s_drop_4:
        number: 1-23
        tags: playfield_active
    s_drop_ace:
        number: 1-24
        tags: playfield_active
    s_drop_2:
        number: 1-25
        tags: playfield_active
    s_drop_3:
        number: 1-26
        tags: playfield_active
    s_drop_6_right:
        number: 1-27
        tags: playfield_active
    s_drop_9:
        number: 1-28
        tags: playfield_active
    s_extra_ball:
        number: 1-29
        tags: playfield_active
    s_ro_2:
        number: 1-30
        tags: playfield_active
    s_ro_king:
        number: 0-21
        tags: playfield_active
    s_ro_queen:
        number: 0-22
        tags: playfield_active
    s_ro_jack:
        number: 0-23
        tags: playfield_active
    s_star1:
        number: 0-16
        tags: playfield_active
    s_star2:
        number: 0-17
        tags: playfield_active
    s_star3:
        number: 0-18
        tags: playfield_active
    s_star4:
        number: 0-19
        tags: playfield_active
    s_star5:
        number: 0-20
        tags: playfield_active
    s_roto:
        number: 0-24
        tags: playfield_active
    s_dingwalls:
        number: 0-26
        tags: playfield_active
    s_tiltbob:
        number: 0-27
        tags: tilt_warning
    s_sling:
        number: 0-2
        tags: playfield_active
    s_pop_left:
        number: 0-0
        tags: playfield_active
    s_pop_right:
        number: 0-1
        tags: playfield_active

# 
#
coils:
    c_drain_eject:
        number: 1-7
        pulse_ms: 200
    c_flipper_left_main:
        number: 1-0
        pulse_ms: 200
        allow_enable: true
        hold_power: 1
    # c_flipper_left_hold:
    #     number: 1-1
    #     pulse_ms: 250
    #     hold_power16: 15
    #     allow_enable: true
    c_flipper_right_main:
        number: 1-2
        pulse_ms: 200
        allow_enable: true
        hold_power: 1
    # c_flipper_right_hold:
    #     number: 1-3
    #     pulse_ms: 250
    #     hold_power16: 15
    #     allow_enable: true
    c_sling:
        number: 0-2
        pulse_ms: 80
    c_leftDTreset:
        number: 1-4
        pulse_ms: 100
    c_midDTreset:
        number: 1-6
        pulse_ms: 80
    c_rightDTreset:
        number: 1-5
        pulse_ms: 80
    c_pop_left:
        number: 0-0
        pulse_ms: 30
    c_pop_right:
        number: 0-1
        pulse_ms: 30
    c_knocker:
        number: 0-7
        pulse_ms: 60
        pulse_events:
            player_games
    c_chime10:
        number: 0-4
        pulse_ms: 60
        pulse_events:
            dingwalls_hit
            slings_hit
            handa_hit
            handb_hit
            handc_hit
            handd_hit
    c_chime100:
        number: 0-5
        pulse_ms: 60
        pulse_events:
            s_pop_left_active
            s_pop_right_active
    c_chime1000:
        number: 0-6
        pulse_ms: 60
        pulse_events:
            player_score
#
autofire_coils:
  slingshot:
    coil: c_sling
    switch: s_sling
  left_pop:
    coil: c_pop_left
    switch: s_pop_left
  right_pop:
    coil: c_pop_right
    switch: s_pop_right
#
drop_targets:
    dt_6:
        switch: s_drop_6
    dt_5:
        switch: s_drop_5
    dt_5b:
        switch: s_drop_5b
    dt_4:
        switch: s_drop_4
    dt_ace:
        switch: s_drop_ace
    dt_2:
        switch: s_drop_2
    dt_3:
        switch: s_drop_3
    dt_6r:
        switch: s_drop_6_right
    dt_9:
        switch: s_drop_9
# 
drop_target_banks:
    dtleft:
        drop_targets: dt_6, dt_5, dt_5b, dt_4
        reset_coil: c_leftDTreset
        reset_events:
            ball_started: 0.25s
            handb_complete: 2.5s
        
    dtmid:
        drop_targets: dt_ace, dt_2, dt_3
        reset_coil: c_midDTreset
        reset_events:
            ball_started: 0.5s
            handa_complete: 2.5s

    dtright:
        drop_targets: dt_6r, dt_9
        reset_coil: c_rightDTreset
        reset_events:
            ball_started: 0.75s
            handc_complete: 2.5s
#
flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        # hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        # hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
#

#
leds:
    l_shootagain:
        number: 33 
        default_color: white
    l_handA3:
        number: 32
        default_color: yellow
    l_handA2:
        number: 31
        default_color: yellow
    l_handA2b:
        number: 30
        default_color: yellow
    l_handAa:
        number: 29
        default_color: yellow
    l_rightout:
        number: 28
        default_color: red
    l_handB4:
        number: 27
        default_color: green
    l_handB5b:
        number: 26
        default_color: green
    l_handB5:
        number: 25
        default_color: green
    l_handB6:
        number: 24
        default_color: green
    l_leftin:
        number: 23
        default_color: red
    l_leftout:
        number: 22
        default_color: blue
    l_DPa:
        number: 20
        default_color: yellow
    l_DPb:
        number: 19
        default_color: green
    l_DPc:
        number: 21
        default_color: red
    l_DPd:
        number: 18
        default_color: blue
    l_handc9:
        number: 17
        default_color: red
    l_handc8:
        number: 16
        default_color: red
    l_handc7:
        number: 15
        default_color: red
    l_handc6:
        number: 14
        default_color: red
    l_handd5:
        number: 11
        default_color: blue
    l_handdj:
        number: 10
        default_color: blue
    l_handdq:
        number: 9
        default_color: blue
    l_handdk:
        number: 8
        default_color: blue
    l_star1:
        number: 7
        default_color: red
    l_star2:
        number: 6
        default_color: red
    l_star3:
        number: 5
        default_color: red
    l_star4:
        number: 4
        default_color: red
    l_star5:
        number: 3
        default_color: red
    l_topK:
        number: 2
        default_color: blue
    l_topQ:
        number: 1
        default_color: blue
    l_topJ:
        number: 0
        default_color: blue
    l_extraball:
        number: 12
        default_color: white
    l_right2:
        number: 13
        default_color: yellow
#

#
displays:
  window:
    width: 1024
    height: 1280
#
window:
  title: NOBS
  width: 1024
  height: 1280    
  resizable: false
  fullscreen: false
  borderless: true
  exit_on_escape: true
  source_display: window
#
slides:

  nobs_running_slide:
    widgets:
      - type: image
        image: nobs_bg
        z: 1
      - type: text
        text: (player1|score)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 0
        y: 930
        font_size: 240
        anchor_x: left
        anchor_y: bottom
        z: 2
      - type: text
        text: (player1|games)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 0
        y: 235        
        font_size: 240
        anchor_x: left
        anchor_y: bottom
        z: 2
      - type: text
        text: (player1|gamescore)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 0
        y: 580        
        font_size: 240
        anchor_x: left
        anchor_y: bottom
        z: 2
      - type: text
        text: (player2|score)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 1024
        y: 930        
        font_size: 240
        anchor_x: right
        anchor_y: bottom
        z: 2
      - type: text
        text: (player2|games)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 1024
        y: 235        
        font_size: 240
        anchor_x: right
        anchor_y: bottom
        z: 2
      - type: text
        text: (player2|gamescore)
        number_grouping: true
        min_digits: 2
        font_name: Ten_segment
        color: blue
        x: 1024
        y: 580        
        font_size: 240
        anchor_x: right
        anchor_y: bottom
        z: 2
      - type: text
        text: (ball)
        font_name: Ten_segment
        color: blue
        x: 520
        y: 55        
        anchor_x: left
        anchor_y: bottom
        font_size: 145
        z: 2
#

