#config_version=6
# NOBS

tilt:
    tilt_warning_events: s_tiltbob_active
    tilt_warning_switch_tag: tilt_warning
    warnings_to_tilt: 3
    reset_warnings_events: ball_ended
    multiple_hit_window: 400ms
    settle_time: 5s


slide_player:
    _overwrite: true
widget_player:
    _overwrite: true

segment_display_player:
    tilt_warning_1: 
      upperpegs:
        flashing: all
        text: "DAN"
        expire: 3s
      uppergames:
        flashing: all
        text: "GER"
        expire: 3s 
    tilt_warning_2: 
      upperpegs:
        flashing: all
        text: "DAN"
        expire: 3s
      uppergames:
        flashing: all
        text: "GER"
        expire: 3s 
      lowerpegs:
        flashing: all
        text: "DAN"
        expire: 3s
      lowergames:
        flashing: all
        text: "GER"
        expire: 3s 
    tilt:
      upperpegs:
        flashing: all
        text: "TIL"
        key: tiltupper
      uppergames:
        flashing: all
        text: "T  "
        key: tiltupper2 
      lowerpegs:
        flashing: all
        text: "  T"
        key: tiltlower
      lowergames:
        flashing: all
        text: "ILT"
        key: tiltlower2
      
    tilt_clear:
      upperpegs:
        action: remove
        key: tiltupper
      uppergames:
        action: remove
        key: tiltupper2
      lowerpegs:
        action: remove 
        key: tiltlower
      lowergames:
        action: remove 
        key: tiltlower2