#config_version=5
# NOBS 

mode:
    start_events: extra_ball_lit
    stop_events: extra_ball_hit
    priority: 100


shots:
    extra_ball:
        switch: s_extra_ball
        reset_events: mode_ebmode_started
        profile: p_onoff
        show_tokens:
            led: l_extraball
